import cPickle as pickle

sag2kenpom = {
    'Oklahoma State': 'Oklahoma St.',
    'Michigan State': 'Michigan St.',
    'Ohio State': 'Ohio St.',
    'Iowa State': 'Iowa St.',
    'Florida State': 'Florida St.',
    'Wichita State': 'Wichita St.',
    'San Diego State': 'San Diego St.',
    'VCU(Va. Commonwealth)': 'VCU',
    'Xavier-Ohio': 'Xavier',
    'Arizona State': 'Arizona St.',
    'Kansas State': 'Kansas St.',
    "Saint Mary's-Cal.": "Saint Mary's",
    'Boise State': 'Boise St.',
    'Indiana State': 'Indiana St.',
    'New Mexico State': 'New Mexico St.',
    'North Dakota State': 'North Dakota St.',
    'Utah State': 'Utah St.',
    'Miami-Florida': 'Miami FL',
    "Saint Joseph's-Pa.": "Saint Joseph's",
    'NC State': 'North Carolina St.',
    'Cleveland State': 'Cleveland St.',
    'Penn State': 'Penn St.',
    'Georgia State': 'Georgia St.',
    'Stony Brook-NY': 'Stony Brook',
    "Hawai'i": 'Hawaii',
    'Louisiana-Lafayette': 'Louisiana Lafayette',
    'Oregon State': 'Oregon St.',
    'Boston U.': 'Boston University',
    'Colorado State': 'Colorado St.',
    'American U.': 'American',
    'Central Florida(UCF)': 'UCF',
    'Kent State': 'Kent St.',
    'Omaha(Neb.-Omaha)': 'Nebraska Omaha',
    'Cal Poly-SLO': 'Cal Poly',
    'NC Central': 'North Carolina Central',
    'Southern California': 'USC',
    'Fort Wayne(IPFW)': 'IPFW',
    'Morehead State': 'Morehead St.',
    'Missouri State': 'Missouri St.',
    'Youngstown State': 'Youngstown St.',
    'Fresno State': 'Fresno St.',
    'Washington State': 'Washington St.',
    'Illinois State': 'Illinois St.',
    'Wright State': 'Wright St.',
    'Arkansas State': 'Arkansas St.',
    'Oakland-Mich.': 'Oakland',
    'Long Beach State': 'Long Beach St.',
    'Weber State': 'Weber St.',
    'Southern U.': 'Southern',
    'South Dakota State': 'South Dakota St.',
    'Mississippi State': 'Mississippi St.',
    'Murray State': 'Murray St.',
    'Sam Houston State': 'Sam Houston St.',
    'St. Francis-NY': 'St. Francis NY',
    'Albany-NY': 'Albany',
    'SE Missouri State(SEMO)': 'Southeast Missouri St.',
    'CS Bakersfield': 'Cal St. Bakersfield',
    'Pennsylvania': 'Penn',
    'Miami-Ohio': 'Miami OH',
    'Loyola-Chicago': 'Loyola Chicago',
    'Norfolk State': 'Norfolk St.',
    'Texas-Arlington': 'UT Arlington',
    'Northwestern State': 'Northwestern St.',
    'NC Asheville': 'UNC Asheville',
    'North Florida(UNF)': 'North Florida',
    'CS Fullerton': 'Cal St. Fullerton',
    'East Tennessee State(ETS': 'East Tennessee St.',
    'Ark.-Little Rock(UALR)': 'Arkansas Little Rock',
    'Monmouth-NJ': 'Monmouth',
    'Louisiana-Monroe': 'Louisiana Monroe',
    'Morgan State': 'Morgan St.',
    'Montana State': 'Montana St.',
    'Gardner-Webb': 'Gardner Webb',
    'San Jose State': 'San Jose St.',
    'CS Northridge': 'Cal St. Northridge',
    'Texas A&M-CorpusChristi': 'Texas A&M Corpus Chris',
    'Idaho State': 'Idaho St.',
    'Texas State': 'Texas St.',
    'Illinois-Chicago': 'Illinois Chicago',
    'Loyola-Maryland': 'Loyola MD',
    'Fla. International': 'FIU',
    'Jackson State': 'Jackson St.',
    'Ball State': 'Ball St.',
    'NC Wilmington': 'UNC Wilmington',
    'Portland State': 'Portland St.',
    'Alabama State': 'Alabama St.',
    'Kansas City(UMKC)': 'UMKC',
    'Savannah State': 'Savannah St.',
    'Chicago State': 'Chicago St.',
    'Coppin State': 'Coppin St.',
    'Long Island U.(LIU)': 'LIU Brooklyn',
    'NC Greensboro': 'UNC Greensboro',
    'Jacksonville State': 'Jacksonville St.',
    'Tennessee State': 'Tennessee St.',
    'NJIT(New Jersey Tech)': 'NJIT',
    'Sacramento State': 'Sacramento St.',
    'NC A&T': 'North Carolina A&T',
    'McNeese State': 'McNeese St.',
    'SE Louisiana': 'Southeastern Louisiana',
    'SIU-Edwardsville': 'SIU Edwardsville',
    'Delaware State': 'Delaware St.',
    'Tennessee-Martin': 'Tennessee Martin',
    'Texas-San Antonio(UTSA)': 'UTSA',
    'Texas-Pan American': 'Texas Pan American',
    'Saint Francis-Pa.': 'St. Francis PA',
    'Central Connecticut St.': 'Central Connecticut',
    'Ark.-Pine Bluff': 'Arkansas Pine Bluff',
    'SC State': 'South Carolina St.',
    'Nicholls State': 'Nicholls St.',
    'Appalachian State': 'Appalachian St.',
    'Alcorn State': 'Alcorn St.',
    'Kennesaw State': 'Kennesaw St.',
    'Md.-Eastern Shore(UMES)': 'Maryland Eastern Shore',
    'Bethune-Cookman': 'Bethune Cookman',
    'Binghamton-NY': 'Binghamton',
    'MVSU(Miss. Valley St.)': 'Mississippi Valley St.',
    'Presbyterian College': 'Presbyterian',
    'Grambling State': 'Grambling St.',
    'UTRGV': 'UT Rio Grande Valley',
    'Little Rock': 'Arkansas Little Rock',  
}

pickle.dump(sag2kenpom, open('sag2kenpom.pickle','w'))
print 'Dumped team names dict to sag2kenpom.pickle'
